### ISSUE TITLE
Add home button above logout button on profile page

### ISSUE THREAD

**Issue by pranaykgupta** [SAAR-IITP/SAAR-IITP#30]
![Screenshot (99)](https://user-images.githubusercontent.com/43784050/70502995-58d26480-1b48-11ea-8d0f-f600172cc2cb.png)
Just above the logout button having the same style as of the logout button.

**Comment by arghac14** [comment]
@pranaykgupta can I work on this?

**Comment by pranaykgupta** [comment]
@arghac14 sure, ping me if you have any questions
