### ISSUE TITLE
Improve timeline section

### ISSUE THREAD

**Issue by pranaykgupta** [SAAR-IITP/SAAR-IITP#31]
**Describe the bug**
The present UI does not looks cool.
Try making something like this [click here](https://previews.123rf.com/images/bryljaev/bryljaev1508/bryljaev150800025/43889258-horizontal-timeline-infographics-design-template.jpg) ( just a sample ) or search for good template on codepen.io .

**Comment by sk044** [comment]
I am interested in this.

**Comment by pranaykgupta** [comment]
@sk044 go ahead
