### ISSUE TITLE
Improve find friend and Alumni near you

### ISSUE THREAD

**Issue by pranaykgupta** [SAAR-IITP/SAAR-IITP#32]
**Describe the bug**
Improve the UI of table in find friend and alumni near you page.
Try making something like this [click here](https://visuallightbox.com/content/data/upload/2018/03/stheme-table.jpg) ( just a sample ) or search for good template on codepen.io .

**Comment by Ankit7Das** [comment]
i'm interested and i wish to work on it

**Comment by pranaykgupta** [comment]
@Ankit7Das go ahead
