### ISSUE TITLE
Create Settings page

### ISSUE THREAD

**Issue by pranaykgupta** [SAAR-IITP/SAAR-IITP#38]
**Present Behaviour**
Update profile, change password and change email ID are present on the profile page (portal.php).
**Expected Behaviour**
Create a settings page and shift them there.

**Comment by arghac14** [comment]
@pranaykgupta can you please elaborate what needs to be done?

**Comment by pranaykgupta** [comment]
@arghac14 create a settings page like shown in the ss of Instagram using our present template with sidebar having options as mentioned in the previous comment along with the home and profile button. Those pages already exist u just need to change sidebar and add relevant buttons.
![Screenshot from 2020-01-20 13-44-42](https://user-images.githubusercontent.com/43784050/72709508-24ac8380-3b8b-11ea-99dc-52f1103deeb7.png)
